import { DesignedFor } from 'components/designed-for'
import { Faq } from 'components/faq'
import { Header } from 'components/header'
import { HowItWorks } from 'components/how-it-works'
import { MainBanner } from 'components/main-banner'
import { Mission } from 'components/mission'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <MainBanner />
        <HowItWorks />
        <Mission />
        <DesignedFor />
        <Faq />
      </main>
    </>
  )
}
